# Standards: 0.1
---
- name: Download repo key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    id: 05CE15085FC09D18E99EFB22684A14CF2582E0C5
    state: present
  tags:
    - telegraf

- name: Add apt repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ telegraf_repo_distribution | default(ansible_distribution) | lower }} {{ telegraf_repo_release | default(ansible_distribution_release) }} stable"
    filename: telegraf
    update_cache: True
    state: present
  tags:
    - telegraf

- name: Install required packages
  loop:
    - telegraf
  package:
    name: "{{ item }}"
    state: present
  tags:
    - telegraf

- name: Combine default lists
  set_fact:
    telegraf_processors: "{{ telegraf_processors_default + telegraf_processors_extra }}"
    telegraf_aggregators: "{{ telegraf_aggregators_default + telegraf_aggregators_extra }}"
    telegraf_plugins: "{{ telegraf_plugins_default + telegraf_plugins_extra }}"
  tags:
    - telegraf

- name: Find template files
  when: telegraf_templates | default(False)
  register: telegraf_templates_find
  delegate_to: localhost
  find:
    paths: "{{ telegraf_templates }}"
    file_type: file
  tags:
    - telegraf

- name: Write template files
  loop: "{{ telegraf_templates_find.files }}"
  loop_control:
    label: "/etc/telegraf/telegraf.d/{{ item.path | basename }}"
  when: telegraf_templates | default(False)
  notify:
    - Restart telegraf
  template:
    src: "{{ item.path }}"
    dest: /etc/telegraf/telegraf.d/{{ item.path | basename }}
  tags:
    - telegraf

- name: Add docker group
  notify:
    - Restart telegraf
  user:
    name: telegraf
    groups: docker
    append: True
  tags:
    - telegraf

- name: Add sudo group
  notify:
    - Restart telegraf
  user:
    name: telegraf
    groups: sudo
    append: True
  tags:
    - telegraf

- name: Write config file
  notify:
    - Restart telegraf
  template:
    src: config.j2
    dest: /etc/telegraf/telegraf.conf
  tags:
    - telegraf

- name: Start telegraf service
  systemd:
    name: telegraf
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - telegraf

...
